
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author user
 */
public class AnaEkran extends javax.swing.JDialog {
    DefaultTableModel model;
    İşlemler işlemler = new İşlemler();
    
    public AnaEkran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) ÇalışanTablosu.getModel();
        çalışanGörüntüle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ÇalışanTablosu = new javax.swing.JTable();
        AramaCubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Mesaj = new javax.swing.JLabel();
        AdT = new javax.swing.JTextField();
        SoyadT = new javax.swing.JTextField();
        DepartmanT = new javax.swing.JTextField();
        MaasT = new javax.swing.JTextField();
        EkleButonu = new javax.swing.JButton();
        GüncelleButonu = new javax.swing.JButton();
        SilmeButonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ÇalışanTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "soyad", "departman", "maas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ÇalışanTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ÇalışanTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ÇalışanTablosu);
        if (ÇalışanTablosu.getColumnModel().getColumnCount() > 0) {
            ÇalışanTablosu.getColumnModel().getColumn(0).setResizable(false);
            ÇalışanTablosu.getColumnModel().getColumn(1).setResizable(false);
            ÇalışanTablosu.getColumnModel().getColumn(2).setResizable(false);
            ÇalışanTablosu.getColumnModel().getColumn(3).setResizable(false);
            ÇalışanTablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        AramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AramaCubuguKeyReleased(evt);
            }
        });

        jLabel1.setText("Ad:");

        jLabel2.setText("Soyad:");

        jLabel3.setText("Departman:");

        jLabel4.setText("Maas:");

        EkleButonu.setText("Ekle");
        EkleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleButonuActionPerformed(evt);
            }
        });

        GüncelleButonu.setText("Güncelle");
        GüncelleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GüncelleButonuActionPerformed(evt);
            }
        });

        SilmeButonu.setText("Çalışan Sil");
        SilmeButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilmeButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AramaCubugu)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(SoyadT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(AdT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DepartmanT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(MaasT, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Mesaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EkleButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GüncelleButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SilmeButonu, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(AramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AdT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EkleButonu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SoyadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DepartmanT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MaasT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(Mesaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(GüncelleButonu)
                        .addGap(18, 18, 18)
                        .addComponent(SilmeButonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        ÇalışanTablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void AramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AramaCubuguKeyReleased
        String arama = AramaCubugu.getText();
        
        dinamikAra(arama);
    }//GEN-LAST:event_AramaCubuguKeyReleased

    private void EkleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleButonuActionPerformed
        Mesaj.setText("");
        
        String ad = AdT.getText();
        String soyad = SoyadT.getText();
        String departman = DepartmanT.getText();
        String maas = MaasT.getText();
        
        if (ad.equals("") || soyad.equals("") || departman.equals("")|| maas.equals("")) {
            JOptionPane.showMessageDialog(this, "Lütfen bütün boşlukları doldurunuz");
        }else{
            işlemler.ÇalışanEkle(ad,soyad,departman,maas);

            çalışanGörüntüle();

            Mesaj.setText("Yeni Çalışan eklendi");
        }
        
    }//GEN-LAST:event_EkleButonuActionPerformed

    private void GüncelleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GüncelleButonuActionPerformed
        Mesaj.setText("");
        
        String ad = AdT.getText();
        String soyad = SoyadT.getText();
        String departman = DepartmanT.getText();
        String maas = MaasT.getText();
        
        int seciliRow = ÇalışanTablosu.getSelectedRow();
        
        if (seciliRow == -1) {
            
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Tablo Boş");
            }else{
                JOptionPane.showMessageDialog(this, "Lütfen tablodan seçim yapınız");
            }
        }else{
            int id = (int)model.getValueAt(seciliRow, 0);
            
            işlemler.çalışanGüncelle(id,ad,soyad,departman,maas);
            
            çalışanGörüntüle();
            
            Mesaj.setText("Güncelleme Başarılı");
            
            AdT.setText("");
            SoyadT.setText("");
            DepartmanT.setText("");
            MaasT.setText("");
        }
        
    }//GEN-LAST:event_GüncelleButonuActionPerformed

    private void ÇalışanTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ÇalışanTablosuMouseClicked
        int secilirow = ÇalışanTablosu.getSelectedRow();
        
        AdT.setText(model.getValueAt(secilirow, 1).toString());
        SoyadT.setText(model.getValueAt(secilirow, 2).toString());
        DepartmanT.setText(model.getValueAt(secilirow, 3).toString());
        MaasT.setText(model.getValueAt(secilirow, 4).toString());
    }//GEN-LAST:event_ÇalışanTablosuMouseClicked

    private void SilmeButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilmeButonuActionPerformed

        int seciliRow = ÇalışanTablosu.getSelectedRow();
        
        if (seciliRow == -1) {
            
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Tablo Boş");
            }else{
                JOptionPane.showMessageDialog(this, "Lütfen tablodan seçim yapınız");
            }
        }else{
            int id = (int)model.getValueAt(seciliRow, 0);
            
            işlemler.çalışanSilme(id);
            
            çalışanGörüntüle();
            
            Mesaj.setText("Başarıyla Silindi!");
            
            AdT.setText("");
            SoyadT.setText("");
            DepartmanT.setText("");
            MaasT.setText("");
        }
        
    }//GEN-LAST:event_SilmeButonuActionPerformed

    public void çalışanGörüntüle(){
        
        model.setRowCount(0);
        
        ArrayList<Calışanlar> ÇalışanlarListesi = new ArrayList<Calışanlar>();
        
        ÇalışanlarListesi = işlemler.ÇalışanlarıGetir();
        
        if (ÇalışanlarListesi != null) {
            for(Calışanlar calışan : ÇalışanlarListesi){
                Object[] eklenecek = {calışan.getId(),calışan.getAd(),calışan.getSoyad(),calışan.getDepartman(),calışan.getMaas()};
                
                model.addRow(eklenecek);
            }
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnaEkran dialog = new AnaEkran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdT;
    private javax.swing.JTextField AramaCubugu;
    private javax.swing.JTextField DepartmanT;
    private javax.swing.JButton EkleButonu;
    private javax.swing.JButton GüncelleButonu;
    private javax.swing.JTextField MaasT;
    private javax.swing.JLabel Mesaj;
    private javax.swing.JButton SilmeButonu;
    private javax.swing.JTextField SoyadT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable ÇalışanTablosu;
    // End of variables declaration//GEN-END:variables
}
